[destination.postgres.credentials]
host = ""
database = ""
username = ""
password = ""
port = ""
connection_timeout = 15

[sources.postgres.credentials]
host = ""
database = ""
username = ""
password = ""
port = ""
chunk_size = 1000000
