---
blank_issues_enabled: true
contact_links:
  - name: Ask a question or get support on dlt Slack
    url: https://join.slack.com/t/dlthub-community/shared_invite/zt-1n5193dbq-rCBmJ6p~ckpSFK4hCF2dYA
    about: Need help or support? Join our dlt community on Slack and get assistance.
