---
blank_issues_enabled: true
contact_links:
  - name: Ask a question or get support on dlt Slack
    url: https://dlthub.com/community
    about: Need help or support? Join our dlt community on Slack and get assistance.
