"""Configuration settings for spatial data sources"""

from typing import Literal

DEFAULT_CHUNK_SIZE = 1000
DEFAULT_GEOMETRY_FORMAT: Literal['wkt', 'wkb', 'geojson', 'geometry'] = 'wkt'
DEFAULT_RASTER_CHUNK_SIZE = (512, 512)

SUPPORTED_OGR_DRIVERS = [
    'ESRI Shapefile',
    'OpenFileGDB',
    'FileGDB',
    'GeoJSON',
    'GeoJSONSeq',
    'GPKG',
    'KML',
    'GML',
    'GPX',
    'DXF',
    'DWG',
    'DGN',
    'MapInfo File',
    'CSV',
    'XLSX',
    'ODS',
    'PostgreSQL',
    'MySQL',
    'SQLite',
    'ODBC',
    'PGeo',
    'MSSQLSpatial',
    'OCI',
    'PCIDSK',
    'WFS',
    'GeoRSS',
    'OSM',
    'VRT',
    'TopoJSON',
    'FlatGeobuf',
    'Parquet',
    'Arrow',
]

SUPPORTED_GDAL_DRIVERS = [
    'GTiff',
    'HFA',
    'AAIGrid',
    'netCDF',
    'HDF4',
    'HDF5',
    'JP2OpenJPEG',
    'JPEG',
    'PNG',
    'GIF',
    'WEBP',
    'BMP',
    'NITF',
    'ECW',
    'MrSID',
    'PCIDSK',
    'VRT',
    'MEM',
    'COG',
    'Zarr',
]

GEOMETRY_TYPES = [
    'Point',
    'LineString',
    'Polygon',
    'MultiPoint',
    'MultiLineString',
    'MultiPolygon',
    'GeometryCollection',
    'Point Z',
    'LineString Z',
    'Polygon Z',
    'MultiPoint Z',
    'MultiLineString Z',
    'MultiPolygon Z',
    'Point M',
    'LineString M',
    'Polygon M',
    'MultiPoint M',
    'MultiLineString M',
    'MultiPolygon M',
    'Point ZM',
    'LineString ZM',
    'Polygon ZM',
    'MultiPoint ZM',
    'MultiLineString ZM',
    'MultiPolygon ZM',
]

OGR_FIELD_TYPE_MAP = {
    0: 'integer',
    1: 'integer_list',
    2: 'double',
    3: 'double_list',
    4: 'string',
    5: 'string_list',
    6: 'binary',
    8: 'integer',
    9: 'date',
    10: 'time',
    11: 'datetime',
    12: 'integer64',
    13: 'integer64_list',
}
