# @@@DLT_SNIPPET_START parallel_config_toml
# `performance-snippets` is the module name and thus config section 
[sources.performance-snippets.data_writer]
file_max_items=100000

[normalize]
workers=3

[normalize.data_writer]
file_max_items=100000

[load]
workers=11

# @@@DLT_SNIPPET_END parallel_config_toml