# here is a file with the secrets for all the example pipelines in `examples` folder

[sources]
# redshift password for query tables example
query_table.credentials.password="..."
query_sql.credentials.password="..."

# google sheets example
[sources.google_spreadsheet.credentials]
project_id="..."
client_email="..."
private_key="..."

[destination]
# all postgres destinations for all examples
postgres.credentials = "postgres://loader:loader@localhost:5432/dlt_data"
# all redshift destinations for all examples
redshift.credentials = "postgres://loader:<password>@<host>.redshift.amazonaws.com:5439/<database name>"

# all the bigquery destinations
[destination.bigquery.credentials]
project_id="..."
client_email="..."
private_key="..."


