[runtime]
dlthub_telemetry=false
dlthub_telemetry_endpoint="https://telemetry-tracker.services4758.workers.dev"

[destination.weaviate]
vectorizer="text2vec-contextionary"
module_config={text2vec-contextionary = { vectorizeClassName = false, vectorizePropertyName = true}}