# Secrets for connecting to local destinations
# Copy into secrets.toml to use

# NOTE: you can start local destinations with "MAKE start-test-containers", docker is required

[destination.clickhouse.credentials]
HOST = "localhost"
DATABASE = "dlt_data"
USERNAME = "loader"
PASSWORD = "loader"
PORT = 9000
HTTP_PORT = 8123
SECURE = 0