fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      # TODO enable check-toml after refactoring snippet checks
      # - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.4
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: check-snippets
        name: check-snippets
        entry: uv run pytest -p xdist -n auto -rn --tb=line -p no:warnings test_snippets.py
        language: python
        pass_filenames: false

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
