fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.4
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: check-snippets
        name: check-snippets
        description: format, type check, and run code snippets
        entry: uv run pytest -m "not example" -p xdist -n auto -rn --tb=no -p no:warnings test_snippets.py --pages
        language: system
        files: ^website/docs/.*\.md$
        types: [markdown]
        pass_filenames: true

  - repo: local
    hooks:
      - id: check-examples
        name: check-examples
        # remove the `xdist` parallelization; this calls the entrypoint for each example.
        entry: uv run pytest -rn --tb=no -p no:warnings test_snippets.py --pages
        language: system
        files: ^website/docs/examples.*\.md$
        types: [markdown]
        pass_filenames: true

  - repo: local
    hooks:
      - id: check-md
        name: check-md
        entry: uv run mdsmith check website/docs --no-color
        language: system
        types: [markdown]
        pass_filenames: false

  # make commands
  - repo: local
    hooks:
      - id: lint-website
        name: lint-website
        entry: make lint-website
        language: system
        pass_filenames: false

      - id: check-orphan-docs
        name: check-orphan-docs
        entry: make check-orphan-docs
        language: system
        pass_filenames: false

      - id: lint-notebooks
        name: lint-notebooks
        entry: make lint-notebooks
        files: ^education/.*\.ipynb$
        types: [jupyter]
        language: system
        pass_filenames: false

      - id: cli-check
        name: cli-check
        entry: uv run --script tools/generate_cli_docs.py website/docs/reference/command-line-interface.md --compare
        language: system
        pass_filenames: false

      - id: validate-molabs
        name: validate-molabs
        entry: make validate-molabs
        files: ^education/.*\.py$
        types: [python]
        language: system
        pass_filenames: false

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
