on:
  workflow_call:
  workflow_dispatch:

jobs:
  docs_build:
    name: build
    runs-on: blacksmith-8vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@v5

      # `uv` is required by some `npm` commands defined in docs/website/package.json
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
          enable-cache: true
          activate-environment: true

      - name: Install node dependencies
        run: cd docs/website && npm install

      - name: Build docs
        run: cd docs/website && npm run build

      - name: Verify docs link redirects
        run: cd docs/website && npm run verify-redirects
