name: master

on:
  pull_request:
    branches: [ master, devel ]

jobs:

  get_docs_changes:
    name: docs changes
    uses: ./.github/workflows/get_docs_changes.yml

  lint:
    name: lint
    needs: get_docs_changes
    if: needs.get_docs_changes.outputs.changes_outside_docs == 'true'
    uses: ./.github/workflows/lint.yml

  test_common:
    needs: lint
    uses: ./.github/workflows/test_common.yml

  test_local_destinations:
    needs: test_common
    uses: ./.github/workflows/test_destinations_local.yml
