name: skip docs changes

on:
  workflow_call:

jobs:
  skip_docs_changes:
    runs-on: ubuntu-latest
    outputs:
      changes_outside_docs: ${{ steps.check_changes.outputs.changes_outside_docs }}
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT

      - name: Check changes outside docs
        id: check_changes
        run: |
          echo "base.sha: ${{ github.event.pull_request.base.sha }}"
          echo "head.sha: ${{ github.event.pull_request.head.sha }}"
          changes_outside_docs=$(
            git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} \
              | grep -v '^docs/' || true
          )
          echo $changes_outside_docs
          if [ -z "$changes_outside_docs" ]; then
            echo "No changes outside docs. Skipping tests."
            echo "changes_outside_docs=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected outside docs."
            echo "changes_outside_docs=true" >> $GITHUB_OUTPUT
          fi
          echo "changes_outside_docs=true" >> $GITHUB_OUTPUT
      - name: Get changes_outside_docs
        run: echo "changes_outside_docs=${{ steps.check_changes.outputs.changes_outside_docs }}"
