name: test airflow integration

on:
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:

jobs:
  get_docs_changes:
    uses: ./.github/workflows/get_docs_changes.yml

  run_airflow:
    name: Tests Airflow integration
    needs: get_docs_changes
    if: needs.get_docs_changes.outputs.changes_outside_docs == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-airflow-runner

      - name: Install dependencies
        run: poetry install --no-interaction --with airflow -E duckdb -E pyarrow

      - run: |
          poetry run pytest tests/helpers/airflow_tests
        name: Run tests
