
name: dest | filesystem

on:
  pull_request:
    branches:
      - master
      - devel
    types:
      - opened
      - synchronize
      - labeled
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:

  DLT_SECRETS_TOML: ${{ secrets.DLT_SECRETS_TOML }}

  # For s3 compatible tests
  TESTS__R2_AWS_ACCESS_KEY_ID: a4950a5003b26f5a71ac97ef3848ff4c
  TESTS__R2_AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
  TESTS__R2_ENDPOINT_URL: https://9830548e4e4b582989be0811f2a0a97f.r2.cloudflarestorage.com
  TESTS__R2_REGION_NAME: us-east-1

  # RUNTIME__SENTRY_DSN: https://6f6f7b6f8e0f458a89be4187603b55fe@o1061158.ingest.sentry.io/4504819859914752
  RUNTIME__LOG_LEVEL: ERROR
  RUNTIME__DLTHUB_TELEMETRY_ENDPOINT: ${{ secrets.RUNTIME__DLTHUB_TELEMETRY_ENDPOINT }}
  # Test redshift and filesystem with all buckets
  # postgres runs again here so we can test on mac/windows
  ACTIVE_DESTINATIONS: "[\"filesystem\", \"dummy\"]"
  # note that all buckets are enabled for testing
  ALL_FILESYSTEM_DRIVERS: "[\"memory\", \"file\", \"r2\", \"s3\", \"gs\", \"az\", \"abfss\", \"gdrive\"]" #excludes sftp

jobs:
  authorize:
    # run when label is assigned OR when we are not a fork
    # see https://iterative.ai/blog/testing-external-contributions-using-github-actions-secrets for inspiration
    if: ${{ github.event.label.name == 'ci from fork' || (github.event.pull_request.head.repo.full_name == github.repository && (github.event.action == 'opened' || github.event.action == 'synchronize'))}}
    runs-on: ubuntu-latest
    steps:
      - run: true

  get_docs_changes:
    name: docs changes
    needs: authorize
    uses: ./.github/workflows/get_docs_changes.yml

  run_loader:
    name: dest | fs tests
    needs: get_docs_changes
    if: needs.get_docs_changes.outputs.changes_outside_docs == 'true'
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    runs-on: "ubuntu-latest"

    steps:

      - name: Check out
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.10
          activate-environment: true
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra gs --extra s3 --extra az --extra parquet --extra duckdb --extra filesystem --group sentry-sdk --group pipeline --extra deltalake --extra pyiceberg --group ibis

      - name: Upgrade sqlalchemy
        run: uv pip install sqlalchemy==2.0.18  # minimum version required by `pyiceberg`

      - name: create secrets.toml
        run: pwd && echo "$DLT_SECRETS_TOML" > tests/.dlt/secrets.toml

      - run: |
          pytest tests/load --ignore tests/load/sources -m "essential"
        name: Run essential tests Linux
        if: ${{ ! (contains(github.event.pull_request.labels.*.name, 'ci full') || github.event_name == 'schedule')}}

      - run: |
          pytest tests/load --ignore tests/load/sources
        name: Run all tests Linux
        if: ${{ contains(github.event.pull_request.labels.*.name, 'ci full') || github.event_name == 'schedule'}}
