# Tests destinations that can run without credentials.
# i.e. local postgres, duckdb, filesystem (with local fs/memory bucket)

name: dest | sqlalchemy mysql and sqlite

on:
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # NOTE: this workflow can't use github secrets!
  # DLT_SECRETS_TOML: ${{ secrets.DLT_SECRETS_TOML }}

  # RUNTIME__SENTRY_DSN: https://6f6f7b6f8e0f458a89be4187603b55fe@o1061158.ingest.sentry.io/4504819859914752
  RUNTIME__LOG_LEVEL: ERROR
  RUNTIME__DLTHUB_TELEMETRY_ENDPOINT: ${{ secrets.RUNTIME__DLTHUB_TELEMETRY_ENDPOINT }}
  ACTIVE_DESTINATIONS: "[\"sqlalchemy\"]"
  ALL_FILESYSTEM_DRIVERS: "[\"memory\", \"file\"]"

jobs:
  get_docs_changes:
    name: docs changes
    uses: ./.github/workflows/get_docs_changes.yml

  run_loader:
    name: dest | sqlalchemy mysql and sqlite
    needs: get_docs_changes
    if: needs.get_docs_changes.outputs.changes_outside_docs == 'true'
    strategy:
      fail-fast: false
      # Run on sqlalchemy 1.4 and 2.0
      matrix:
        sqlalchemy: [1.4, 2]
    defaults:
      run:
        shell: bash
    runs-on: "ubuntu-latest"

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dlt_data
          MYSQL_USER: loader
          MYSQL_PASSWORD: loader
        ports:
          - 3306:3306
        # Wait for the service to be ready before completing the job
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.10
          activate-environment: true
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra parquet --extra filesystem --extra sqlalchemy --extra cli --group sentry-sdk --group pipeline --group ibis && uv pip install pymysql && uv pip install "sqlalchemy==${{ matrix.sqlalchemy }}"

      - name: create secrets.toml
        run: pwd && echo "$DLT_SECRETS_TOML" > tests/.dlt/secrets.toml

      # always run full suite, also on branches
      - run: pytest tests/load --ignore tests/load/sources
        name: Run tests Linux
