name: tools | airflow

on:
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  get_docs_changes:
    name: docs changes
    uses: ./.github/workflows/get_docs_changes.yml

  run_airflow:
    name: tools | airflow tests
    needs: get_docs_changes
    if: needs.get_docs_changes.outputs.changes_outside_docs == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.10
          activate-environment: true
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra duckdb --extra parquet --group airflow --group pipeline  --group sentry-sdk

      - run: |
          pytest tests/helpers/airflow_tests
        name: Run tests
