
name: dest | athena

on:
  pull_request:
    branches:
      - master
      - devel
    types:
      - opened
      - synchronize
      - labeled
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DLT_SECRETS_TOML: ${{ secrets.DLT_SECRETS_TOML }}

  # RUNTIME__SENTRY_DSN: https://6f6f7b6f8e0f458a89be4187603b55fe@o1061158.ingest.sentry.io/4504819859914752
  RUNTIME__LOG_LEVEL: ERROR
  RUNTIME__DLTHUB_TELEMETRY_ENDPOINT: ${{ secrets.RUNTIME__DLTHUB_TELEMETRY_ENDPOINT }}
  ACTIVE_DESTINATIONS: "[\"athena\"]"
  ALL_FILESYSTEM_DRIVERS: "[\"memory\"]"
  EXCLUDED_DESTINATION_CONFIGURATIONS: "[\"athena-parquet-iceberg-no-staging-iceberg\", \"athena-parquet-iceberg-staging-iceberg\"]"

jobs:
  authorize:
    # run when label is assigned OR when we are not a fork
    if: ${{ github.event.label.name == 'ci from fork' || (github.event.pull_request.head.repo.full_name == github.repository && (github.event.action == 'opened' || github.event.action == 'synchronize'))}}
    runs-on: ubuntu-latest
    steps:
      - run: true

  get_docs_changes:
    name: docs changes
    needs: authorize
    uses: ./.github/workflows/get_docs_changes.yml

  run_loader:
    name: dest | athena tests
    needs: get_docs_changes
    if: needs.get_docs_changes.outputs.changes_outside_docs == 'true'
    defaults:
      run:
        shell: bash
    runs-on: "ubuntu-latest"

    steps:

      - name: Check out
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.10
          activate-environment: true
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra athena --group sentry-sdk --group pipeline --group ibis

      - name: create secrets.toml
        run: pwd && echo "$DLT_SECRETS_TOML" > tests/.dlt/secrets.toml

      - run: |
          pytest tests/load --ignore tests/load/sources -m "essential"
        name: Run essential tests Linux
        if: ${{ ! (contains(github.event.pull_request.labels.*.name, 'ci full') || !github.event_name == 'schedule')}}

      - run: |
          pytest tests/load --ignore tests/load/sources
        name: Run all tests Linux
        if: ${{ contains(github.event.pull_request.labels.*.name, 'ci full') || github.event_name == 'schedule'}}
